### ISSUE TITLE
C++ and Unity sections on firebaseopensource.com

### ISSUE THREAD

**Issue by stewartmiles** [firebase/firebaseopensource.com#12]
Looks like we're missing sections for game developer focused content.

**Comment by samtstern** [comment]
@stewartmiles would you like to see one new "Games" section or separate "C++" and "Unity" sections?

**Comment by stewartmiles** [comment]
@kiwihilton what do you think?

**Comment by kiwihilton** [comment]
My preference would be a master 'Games' section and then split out to 'Unity' and 'C++', we may add other platforms and it would be nice to nest those under a catch all.

**Comment by samtstern** [comment]
Sorry not sure what you mean.  The way it works is each repo can be tagged with one or more "platforms" but each platform section on the homepage can only show a single tag (mostly due to how Firestore queries work).

So options are:

  * Tag each games repo with one of `unity` or `cpp`, add two sections to the site
  * Tag each games repo with only `games`, add one section to the site
  * Tag each games repo with one of `unity` or `cpp` and also with `games`.  For now show a `games` section on the site but have the data in place to split it up later if it's too big.

**Comment by samtstern** [comment]
@kiwihilton right now no, each circle icon represents one github repo.

**Comment by kiwihilton** [comment]
Sgtm!

**Comment by samtstern** [comment]
@kiwihilton @stewartmiles Games section is launched

https://firebaseopensource.com/projects/firebase/cocos2dx-cpp-sample/
https://firebaseopensource.com/platform/Games

Content for these pages is stored in the github repos themselves.  If you want to customize it, add a `.opensource/project.json` file like this:
https://github.com/firebase/quickstart-android/blob/master/.opensource/project.json

That lets you tell us which MD file should make your root page, which other MD files we should render, and what platforms you belong to.

**Comment by kiwihilton** [comment]
Awesome! Thanks so much, that was quick! :)

**Comment by stewartmiles** [comment]
Thanks @samtstern much appreciated.
