### ISSUE TITLE
Pages are still making requests to Firestore

### ISSUE THREAD

**Issue by samtstern** [firebase/firebaseopensource.com#163]
**What Happened?**
The site should be static rendered but there are still XHR requests to Firestore

**What Did You Expect to Happen**
All data 100% rendered on page

**Screenshot (If Applicable)**
<img width="1437" alt="Screen Shot 2020-05-20 at 9 29 06 AM" src="https://user-images.githubusercontent.com/8466666/82451807-76531500-9a7c-11ea-8f73-35ba8f561d12.png">

**Comment by samtstern** [comment]
@lupas do you know why this is happening?

**Comment by samtstern** [comment]
I guess it's because asyncData is called on the client: https://nuxtjs.org/api/

Can we prevent that?

**Comment by lupas** [comment]
@samtstern 
This is how nuxt i.e. nuxt-generate works.
https://nuxtjs.org/guide#static-generated-pre-rendering-

The initial page load is served from the pre-rendered html file, while all further route changes are served dynamically.

It's rather a feature than a bug of nuxt actually... :P

Imho it makes the experience smoother, but depending on the use case it's not necessarily the most optimal thing. Not sure if it makes a big difference here?

An easy solution to fix this would be to just use regular <a> links instead of <router-link> resp. <nuxt-link>'s.

**Comment by samtstern** [comment]
Yeah in this case there's no reason to make those requests since Firestore is not going to have any new data.  The Firestore data is updated every 24 hours and so is the website.

Can you explain a little more about the "regular links" part?

**Comment by lupas** [comment]
@samtstern 
Even though we pre-render the pages, we actually have a Single Page Application that uses vue-router in the background. So if we use "router-link" (or for nuxt we can use [nuxt-link](https://nuxtjs.org/api/components-nuxt-link#__layout)), as we do now, the routing will be handled by Javascript and not by actually loading a new page -> SPA in a nutshell?

If we use regular "a href" links, the page will just load the new pre-rendered html file for the new route and not make any requests to Firestore. So problem solved.

It's actually a pretty clever little thing this nuxt generate.

In this particular case I agree with you, there's probably not many benefits in using SPA routing.

**Comment by samtstern** [comment]
👍 thank you for explaining!  Definitely useful to know, I think I'll try moving things back to `<a>` links for this project but I think you're right in most cases `nuxt-link` is the right move.

**Comment by lupas** [comment]
Alright, sounds good! Hope that's not too much effort, let me know if there's more weird stuff happening ;)
